import Head from 'next/head';
import React from 'react';
import { TableColumn } from 'react-data-table-component';
import useSwr from 'swr';
import { CustomTable } from '../components/CustomTable/Table';

const fetcher = (url: any) => fetch(url).then((res) => res.json());

type DataRow = {
	name: string;
	place: string;
	animal: string;
	food: string;
	things: string;
};

const Home = () => {
	const { data, error } = useSwr('/api/users', fetcher);

	if (error) return <div>Failed to load users</div>;
	if (!data) return <div>Loading...</div>;

	const columns: TableColumn<DataRow>[] = [
		{
			name: 'Name',
			sortable: true,
			cell: (row) => <p>{row.name}</p>,
		},
		{
			name: 'Place',
			sortable: true,
			cell: (row) => <p>{row.place}</p>,
		},
		{
			name: 'Animal',
			sortable: true,
			cell: (row) => <p>{row.animal}</p>,
		},
		{
			name: 'Food',
			sortable: true,
			cell: (row) => <p>{row.food}</p>,
		},
		{
			name: 'Thing',
			sortable: true,
			cell: (row) => <p>{row.things}</p>,
		},
	];

	return (
		<div>
			<Head>
				<title>Ryffable Project</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='mx-auto px-8 xl:w-2/3 2xl:w-1/2 my-20'>
				<h1 className='text-center font-bold text-4xl text-cyan-400 mb-20 transition-colors'>
					Ryffable Take Home Challenge
				</h1>

				<CustomTable columns={columns} data={data} />
			</main>
		</div>
	);
};

export default Home;
